services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: store
      MARIADB_USER: store_admin
      MARIADB_PASSWORD: "!StringP@ssw@rd"
      MARIADB_ROOT_PASSWORD: "!StringP@ssw@rd"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local